### PR TITLE
Change .deb JDK dependency to java8-sdk-headless

### LINKED ISSUE #7: Compatibility with AdoptOpenJDK
I'm currently running Nexus OSS from the regular tar.gz download (not APT/RPM installer) and it's running fine on `adoptopenjdk-8-hotspot` package from [AdoptOpenJDK APT repository](https://adoptopenjdk.net/installation.html#linux-pkg) from https://adoptopenjdk.net/.

I've noticed that the .deb package has a direct dependency on `openjdk-8-jdk-headless` from the Debian repositories.  This will prevent it being installed on the current Debian stable release, which has defaulted to Java 11.

Both `openjdk-8-jdk-headless` and `adoptopenjdk-8-hotspot` packages show `Provides: java8-sdk-headless`. Can this package be updated to have a dependency on `java8-sdk-headless` instead of `openjdk-8-jdk-headless`?

### PR DESCRIPTION
**Pull request by wwuck**
Allows for installing from AdoptOpenJDK.

Fixes #7

### CODE REVIEW

**Comment by wwuck** [comment]
Signed

**Comment by bhamail** [comment]
@wwuck Sorry for the slow response on this. May I ask why you want the change from openjdk `openjdk-8-jdk-headless` to java8 `java8-sdk-headless`? If the java8 is the Oracle flavor, the licensing for that is no longer "open", and most cases require the use of the openjdk. 

Oh wait, I just read Issue #7, and I'm guessing this PR relates to that. Still would like to confirm we're not using the Oracle licensed flavor, but an "openjdk" flavor.

**Comment by wwuck** [comment]
Hi @bhamail,

[AdoptOpenJDK](https://adoptopenjdk.net/about.html) provides pre-built binaries for OpenJDK.

**Comment by wwuck** [comment]
Their website says [the project is joining the Eclipse Foundation](https://blog.adoptopenjdk.net/2020/06/adoptopenjdk-to-join-the-eclipse-foundation/) and that there will be a renaming of the project and their provided packages at some point in the future, but that shouldn't affect this change as this doesn't reference their package name directly.

**Comment by bhamail** [comment]
Just a note to say this change looks good to me, and I plan to do some testing of this change on Thursday. I haven't forgotten about it.

**Comment by bhamail** [comment]
In doing some more testing, there appear to be cases where the `openjdk-8-jdk-headless` package is still the thing that had to be installed. How about changing the CONTROL file to use `OR`? e.g. `openjdk-8-jdk-headless | java8-sdk-headless`

```
sed -i -e 's/Depends: \${shlibs:Depends}/Depends: \${shlibs:Depends}, openjdk-8-jdk-headless | java8-sdk-headless/' "${RPM_BASENAME}/debian/control"
```

If you can push that change to this PR, I'll merge it and we can fix it if needed.

(I'll be very happy when the jdk8 requirement is in the rear view mirror.)

**Review by bhamail — APPROVED** [review]
Thanks!

**Pull request merged**
